name: pure_plate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1

  # State Management
  provider: ^6.1.2

  # Icons
  cupertino_icons: ^1.0.8

  # Date formatting
  intl: ^0.19.0

  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # FOR UNIT TESTTING (added by mustafa)
  mocktail: ^1.0.4 

flutter:
  uses-material-design: true

  # Asset Images
  assets:
    - lib/assets/images/default_profile.png

  # Custom Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
